"""add operator.password_hash

Revision ID: 4d2b0864b0af
Revises: c46233bc9881
Create Date: 2026-05-27 08:15:26.323453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d2b0864b0af"
down_revision: Union[str, None] = "c46233bc9881"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operator", sa.Column("password_hash", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operator", "password_hash")
    # ### end Alembic commands ###
