"""initial_schema

Revision ID: c46233bc9881
Revises:
Create Date: 2026-05-26 17:49:04.972041

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c46233bc9881"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("canonical_domain", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operator",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "submission",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("company_name", sa.String(length=512), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("work_email", sa.String(length=320), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("tax_id", sa.String(length=128), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column("requester_full_name", sa.String(length=255), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("extra_metadata", sa.JSON(), nullable=True),
        sa.Column("source_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("forwarded_headers", sa.JSON(), nullable=True),
        sa.Column("endpoint", sa.String(length=256), nullable=True),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_entity_id"), "submission", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_submission_idempotency_key"),
        "submission",
        ["idempotency_key"],
        unique=True,
    )
    op.create_table(
        "verification_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("submission_id", sa.String(length=36), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("source_availability", sa.JSON(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["verification_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_run_entity_id"),
        "verification_run",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_run_submission_id"),
        "verification_run",
        ["submission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_run_supersedes_id"),
        "verification_run",
        ["supersedes_id"],
        unique=False,
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("operator_id", sa.String(length=36), nullable=True),
        sa.Column("verification_run_id", sa.String(length=36), nullable=True),
        sa.Column("submission_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_run_id"],
            ["verification_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_event_event_type"), "audit_event", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_occurred_at"), "audit_event", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_operator_id"), "audit_event", ["operator_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_event_submission_id"),
        "audit_event",
        ["submission_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_event_verification_run_id"),
        "audit_event",
        ["verification_run_id"],
        unique=False,
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verification_run_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=128), nullable=True),
        sa.Column("raw_value", sa.Text(), nullable=True),
        sa.Column("normalized_value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=True),
        sa.Column("attribution", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["verification_run_id"],
            ["verification_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_verification_run_id"),
        "evidence",
        ["verification_run_id"],
        unique=False,
    )
    op.create_table(
        "review",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verification_run_id", sa.String(length=36), nullable=False),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("corrections", sa.JSON(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_run_id"],
            ["verification_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_operator_id"), "review", ["operator_id"], unique=False
    )
    op.create_index(
        op.f("ix_review_verification_run_id"),
        "review",
        ["verification_run_id"],
        unique=True,
    )
    op.create_table(
        "risk_assessment",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verification_run_id", sa.String(length=36), nullable=False),
        sa.Column("entity_score", sa.Float(), nullable=True),
        sa.Column("infrastructure_score", sa.Float(), nullable=True),
        sa.Column("representation_score", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Float(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("triage_tier", sa.String(length=32), nullable=True),
        sa.Column("contributing_signals", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["verification_run_id"],
            ["verification_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_assessment_verification_run_id"),
        "risk_assessment",
        ["verification_run_id"],
        unique=False,
    )
    op.create_table(
        "field_comparison",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verification_run_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=True),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("submitted_value", sa.Text(), nullable=True),
        sa.Column("discovered_value", sa.Text(), nullable=True),
        sa.Column("match_status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_run_id"],
            ["verification_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_comparison_evidence_id"),
        "field_comparison",
        ["evidence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_comparison_verification_run_id"),
        "field_comparison",
        ["verification_run_id"],
        unique=False,
    )
    op.create_table(
        "report",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verification_run_id", sa.String(length=36), nullable=False),
        sa.Column("risk_assessment_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("section_statuses", sa.JSON(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["risk_assessment_id"],
            ["risk_assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["verification_run_id"],
            ["verification_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_report_risk_assessment_id"),
        "report",
        ["risk_assessment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_verification_run_id"),
        "report",
        ["verification_run_id"],
        unique=True,
    )
    op.create_table(
        "risk_assessment_evidence",
        sa.Column("risk_assessment_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_assessment_id"],
            ["risk_assessment.id"],
        ),
        sa.PrimaryKeyConstraint("risk_assessment_id", "evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_assessment_evidence")
    op.drop_index(op.f("ix_report_verification_run_id"), table_name="report")
    op.drop_index(op.f("ix_report_risk_assessment_id"), table_name="report")
    op.drop_table("report")
    op.drop_index(
        op.f("ix_field_comparison_verification_run_id"), table_name="field_comparison"
    )
    op.drop_index(
        op.f("ix_field_comparison_evidence_id"), table_name="field_comparison"
    )
    op.drop_table("field_comparison")
    op.drop_index(
        op.f("ix_risk_assessment_verification_run_id"), table_name="risk_assessment"
    )
    op.drop_table("risk_assessment")
    op.drop_index(op.f("ix_review_verification_run_id"), table_name="review")
    op.drop_index(op.f("ix_review_operator_id"), table_name="review")
    op.drop_table("review")
    op.drop_index(op.f("ix_evidence_verification_run_id"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_audit_event_verification_run_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_submission_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_operator_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_occurred_at"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_event_type"), table_name="audit_event")
    op.drop_table("audit_event")
    op.drop_index(
        op.f("ix_verification_run_supersedes_id"), table_name="verification_run"
    )
    op.drop_index(
        op.f("ix_verification_run_submission_id"), table_name="verification_run"
    )
    op.drop_index(op.f("ix_verification_run_entity_id"), table_name="verification_run")
    op.drop_table("verification_run")
    op.drop_index(op.f("ix_submission_idempotency_key"), table_name="submission")
    op.drop_index(op.f("ix_submission_entity_id"), table_name="submission")
    op.drop_table("submission")
    op.drop_table("operator")
    op.drop_table("entity")
    # ### end Alembic commands ###
