"""add screening tables (IS1-T3, ticket 0031)

Revision ID: d9e3f4a5b6c7
Revises: c8d2e3f4a5b6
Create Date: 2026-09-24 15:00:45.535597

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d9e3f4a5b6c7"
down_revision: Union[str, None] = "c8d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screening_rule_version",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by_operator_id", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_operator_id"],
            ["operator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "screening_subject",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("pii_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("pii_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("kyb_entity_id", sa.String(length=36), nullable=True),
        sa.Column("api_client_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_operator_id", sa.String(length=36), nullable=True),
        sa.Column("relationship_ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shredded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["api_client_id"],
            ["api_client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_operator_id"],
            ["operator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kyb_entity_id"],
            ["entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_subject_api_client_id"),
        "screening_subject",
        ["api_client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_subject_kyb_entity_id"),
        "screening_subject",
        ["kyb_entity_id"],
        unique=False,
    )
    op.create_table(
        "screening_run",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("subject_id", sa.String(length=36), nullable=False),
        sa.Column("rule_version_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=32), nullable=False),
        sa.Column("triggered_by_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("prior_run_id", sa.String(length=36), nullable=True),
        sa.Column("source_availability", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prior_run_id"],
            ["screening_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["screening_rule_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["screening_subject.id"],
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_snapshot_id"],
            ["list_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_run_subject_id"),
        "screening_run",
        ["subject_id"],
        unique=False,
    )
    op.create_table(
        "screening_candidate",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("watchlist_record_id", sa.String(length=36), nullable=False),
        sa.Column("blocking_keys", sa.JSON(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["screening_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["watchlist_record_id"],
            ["watchlist_record.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_candidate_run_id"),
        "screening_candidate",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "screening_decision",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("rule_version_id", sa.String(length=36), nullable=False),
        sa.Column("system_disposition", sa.String(length=16), nullable=False),
        sa.Column("auto_closed", sa.Boolean(), nullable=False),
        sa.Column("snapshot_ids", sa.JSON(), nullable=False),
        sa.Column("thresholds", sa.JSON(), nullable=False),
        sa.Column("terms", sa.JSON(), nullable=False),
        sa.Column("top_score", sa.Float(), nullable=True),
        sa.Column("frozen_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("frozen_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("normalizer_version", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rule_version_id"],
            ["screening_rule_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["screening_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_decision_run_id"),
        "screening_decision",
        ["run_id"],
        unique=True,
    )
    op.create_table(
        "screening_claim",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=True),
        sa.Column("about", sa.String(length=16), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("locator", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["screening_candidate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["screening_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_claim_run_id"), "screening_claim", ["run_id"], unique=False
    )
    op.create_table(
        "screening_disposition",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decision_id", sa.String(length=36), nullable=False),
        sa.Column("disposition", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["screening_decision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_disposition_decision_id"),
        "screening_disposition",
        ["decision_id"],
        unique=False,
    )
    op.create_table(
        "screening_term",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("claim_ids", sa.JSON(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["screening_candidate.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["screening_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_term_candidate_id"),
        "screening_term",
        ["candidate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_screening_term_run_id"), "screening_term", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_screening_term_run_id"), table_name="screening_term")
    op.drop_index(op.f("ix_screening_term_candidate_id"), table_name="screening_term")
    op.drop_table("screening_term")
    op.drop_index(
        op.f("ix_screening_disposition_decision_id"), table_name="screening_disposition"
    )
    op.drop_table("screening_disposition")
    op.drop_index(op.f("ix_screening_claim_run_id"), table_name="screening_claim")
    op.drop_table("screening_claim")
    op.drop_index(op.f("ix_screening_decision_run_id"), table_name="screening_decision")
    op.drop_table("screening_decision")
    op.drop_index(
        op.f("ix_screening_candidate_run_id"), table_name="screening_candidate"
    )
    op.drop_table("screening_candidate")
    op.drop_index(op.f("ix_screening_run_subject_id"), table_name="screening_run")
    op.drop_table("screening_run")
    op.drop_index(
        op.f("ix_screening_subject_kyb_entity_id"), table_name="screening_subject"
    )
    op.drop_index(
        op.f("ix_screening_subject_api_client_id"), table_name="screening_subject"
    )
    op.drop_table("screening_subject")
    op.drop_table("screening_rule_version")
    # ### end Alembic commands ###
