"""Country names → ISO 3166-1 alpha-2 for list and subject data (ticket 0038).

Watchlists write nationality many ways ("Russia", "RUSSIAN FEDERATION",
"Korea, North", "DPRK", "Iran (Islamic Republic of)"). This table maps them
to ISO-2 codes so nationality terms compare like with like. The names were
cross-checked against the countryIso2Code/countryDescription pairs published
in the EU sanctions file, and the aliases come from unmapped values
observed in the live OFAC, UN and UK files (2026-09-24).
"""

from __future__ import annotations

import re

from anyascii import anyascii

ISO2: dict[str, str] = {
    "AD": "Andorra",
    "AE": "United Arab Emirates",
    "AF": "Afghanistan",
    "AG": "Antigua and Barbuda",
    "AI": "Anguilla",
    "AL": "Albania",
    "AM": "Armenia",
    "AO": "Angola",
    "AQ": "Antarctica",
    "AR": "Argentina",
    "AS": "American Samoa",
    "AT": "Austria",
    "AU": "Australia",
    "AW": "Aruba",
    "AX": "Aland Islands",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BB": "Barbados",
    "BD": "Bangladesh",
    "BE": "Belgium",
    "BF": "Burkina Faso",
    "BG": "Bulgaria",
    "BH": "Bahrain",
    "BI": "Burundi",
    "BJ": "Benin",
    "BL": "Saint Barthelemy",
    "BM": "Bermuda",
    "BN": "Brunei Darussalam",
    "BO": "Bolivia",
    "BQ": "Bonaire, Sint Eustatius and Saba",
    "BR": "Brazil",
    "BS": "Bahamas",
    "BT": "Bhutan",
    "BV": "Bouvet Island",
    "BW": "Botswana",
    "BY": "Belarus",
    "BZ": "Belize",
    "CA": "Canada",
    "CC": "Cocos (Keeling) Islands",
    "CD": "Democratic Republic of the Congo",
    "CF": "Central African Republic",
    "CG": "Congo",
    "CH": "Switzerland",
    "CI": "Cote d'Ivoire",
    "CK": "Cook Islands",
    "CL": "Chile",
    "CM": "Cameroon",
    "CN": "China",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "CU": "Cuba",
    "CV": "Cabo Verde",
    "CW": "Curacao",
    "CX": "Christmas Island",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DE": "Germany",
    "DJ": "Djibouti",
    "DK": "Denmark",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "DZ": "Algeria",
    "EC": "Ecuador",
    "EE": "Estonia",
    "EG": "Egypt",
    "EH": "Western Sahara",
    "ER": "Eritrea",
    "ES": "Spain",
    "ET": "Ethiopia",
    "FI": "Finland",
    "FJ": "Fiji",
    "FK": "Falkland Islands",
    "FM": "Micronesia",
    "FO": "Faroe Islands",
    "FR": "France",
    "GA": "Gabon",
    "GB": "United Kingdom",
    "GD": "Grenada",
    "GE": "Georgia",
    "GF": "French Guiana",
    "GG": "Guernsey",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GL": "Greenland",
    "GM": "Gambia",
    "GN": "Guinea",
    "GP": "Guadeloupe",
    "GQ": "Equatorial Guinea",
    "GR": "Greece",
    "GS": "South Georgia and the South Sandwich Islands",
    "GT": "Guatemala",
    "GU": "Guam",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HK": "Hong Kong",
    "HM": "Heard Island and McDonald Islands",
    "HN": "Honduras",
    "HR": "Croatia",
    "HT": "Haiti",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IM": "Isle of Man",
    "IN": "India",
    "IO": "British Indian Ocean Territory",
    "IQ": "Iraq",
    "IR": "Iran",
    "IS": "Iceland",
    "IT": "Italy",
    "JE": "Jersey",
    "JM": "Jamaica",
    "JO": "Jordan",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KH": "Cambodia",
    "KI": "Kiribati",
    "KM": "Comoros",
    "KN": "Saint Kitts and Nevis",
    "KP": "North Korea",
    "KR": "South Korea",
    "KW": "Kuwait",
    "KY": "Cayman Islands",
    "KZ": "Kazakhstan",
    "LA": "Laos",
    "LB": "Lebanon",
    "LC": "Saint Lucia",
    "LI": "Liechtenstein",
    "LK": "Sri Lanka",
    "LR": "Liberia",
    "LS": "Lesotho",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "LY": "Libya",
    "MA": "Morocco",
    "MC": "Monaco",
    "MD": "Moldova",
    "ME": "Montenegro",
    "MF": "Saint Martin",
    "MG": "Madagascar",
    "MH": "Marshall Islands",
    "MK": "North Macedonia",
    "ML": "Mali",
    "MM": "Myanmar",
    "MN": "Mongolia",
    "MO": "Macao",
    "MP": "Northern Mariana Islands",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MS": "Montserrat",
    "MT": "Malta",
    "MU": "Mauritius",
    "MV": "Maldives",
    "MW": "Malawi",
    "MX": "Mexico",
    "MY": "Malaysia",
    "MZ": "Mozambique",
    "NA": "Namibia",
    "NC": "New Caledonia",
    "NE": "Niger",
    "NF": "Norfolk Island",
    "NG": "Nigeria",
    "NI": "Nicaragua",
    "NL": "Netherlands",
    "NO": "Norway",
    "NP": "Nepal",
    "NR": "Nauru",
    "NU": "Niue",
    "NZ": "New Zealand",
    "OM": "Oman",
    "PA": "Panama",
    "PE": "Peru",
    "PF": "French Polynesia",
    "PG": "Papua New Guinea",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PM": "Saint Pierre and Miquelon",
    "PN": "Pitcairn",
    "PR": "Puerto Rico",
    "PS": "Palestine",
    "PT": "Portugal",
    "PW": "Palau",
    "PY": "Paraguay",
    "QA": "Qatar",
    "RE": "Reunion",
    "RO": "Romania",
    "RS": "Serbia",
    "RU": "Russia",
    "RW": "Rwanda",
    "SA": "Saudi Arabia",
    "SB": "Solomon Islands",
    "SC": "Seychelles",
    "SD": "Sudan",
    "SE": "Sweden",
    "SG": "Singapore",
    "SH": "Saint Helena",
    "SI": "Slovenia",
    "SJ": "Svalbard and Jan Mayen",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "SN": "Senegal",
    "SO": "Somalia",
    "SR": "Suriname",
    "SS": "South Sudan",
    "ST": "Sao Tome and Principe",
    "SV": "El Salvador",
    "SX": "Sint Maarten",
    "SY": "Syria",
    "SZ": "Eswatini",
    "TC": "Turks and Caicos Islands",
    "TD": "Chad",
    "TF": "French Southern Territories",
    "TG": "Togo",
    "TH": "Thailand",
    "TJ": "Tajikistan",
    "TK": "Tokelau",
    "TL": "Timor-Leste",
    "TM": "Turkmenistan",
    "TN": "Tunisia",
    "TO": "Tonga",
    "TR": "Turkey",
    "TT": "Trinidad and Tobago",
    "TV": "Tuvalu",
    "TW": "Taiwan",
    "TZ": "Tanzania",
    "UA": "Ukraine",
    "UG": "Uganda",
    "UM": "United States Minor Outlying Islands",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VA": "Holy See",
    "VC": "Saint Vincent and the Grenadines",
    "VE": "Venezuela",
    "VG": "British Virgin Islands",
    "VI": "US Virgin Islands",
    "VN": "Vietnam",
    "VU": "Vanuatu",
    "WF": "Wallis and Futuna",
    "WS": "Samoa",
    "XK": "Kosovo",
    "YE": "Yemen",
    "YT": "Mayotte",
    "ZA": "South Africa",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
    # Historic codes still seen on lists.
    "AN": "Netherlands Antilles",
    "YU": "Yugoslavia",
    "SU": "Soviet Union",
    "CS": "Serbia and Montenegro",
}

ALIASES: dict[str, str] = {
    "russian federation": "RU",
    "iran islamic republic of": "IR",
    "islamic republic of iran": "IR",
    "syrian arab republic": "SY",
    "korea north": "KP",
    "dprk": "KP",
    "democratic people s republic of korea": "KP",
    "korea democratic people s republic of": "KP",
    "korea south": "KR",
    "republic of korea": "KR",
    "korea republic of": "KR",
    "burma": "MM",
    "palestinian": "PS",
    "possibly palestinian": "PS",
    "palestinian territories": "PS",
    "occupied palestinian territory": "PS",
    "congo democratic republic of the": "CD",
    "congo democratic republic": "CD",
    "democratic republic of congo": "CD",
    "drc": "CD",
    "congo republic of the": "CG",
    "republic of the congo": "CG",
    "bosnia and herzegowina": "BA",
    "bosnia herzegovina": "BA",
    "united kingdom of great britain and northern ireland": "GB",
    "great britain": "GB",
    "uk": "GB",
    "england": "GB",
    "united states of america": "US",
    "usa": "US",
    "north macedonia the republic of": "MK",
    "macedonia": "MK",
    "the former yugoslav republic of macedonia": "MK",
    "gambia the": "GM",
    "the gambia": "GM",
    "guinea bissau": "GW",
    "tanzania united republic of": "TZ",
    "united republic of tanzania": "TZ",
    "moldova republic of": "MD",
    "republic of moldova": "MD",
    "viet nam": "VN",
    "lao people s democratic republic": "LA",
    "cote d ivoire": "CI",
    "ivory coast": "CI",
    "turkiye": "TR",
    "czech republic": "CZ",
    "swaziland": "SZ",
    "cape verde": "CV",
    "brunei": "BN",
    "vatican": "VA",
    "macau": "MO",
    "venezuela bolivarian republic of": "VE",
    "bolivia plurinational state of": "BO",
    "micronesia federated states of": "FM",
    "timor leste": "TL",
    "east timor": "TL",
    "ussr": "SU",
    "soviet union": "SU",
    "former soviet union": "SU",
    "federal republic of yugoslavia": "YU",
    "serbia and montenegro": "CS",
    # EU file spellings.
    "congo democratic republic of was zaire": "CD",
    "congo people s republic of": "CG",
    "palestinian territory occupied": "PS",
    "virgin islands british": "VG",
    # Other observed variants and demonyms.
    "state of palestine": "PS",
    "region gaza": "PS",
    "russian": "RU",
    "republic of ireland": "IE",
    "britain": "GB",
    "british": "GB",
    "german": "DE",
    "moldovan": "MD",
}

_BY_NAME = {re.sub(r"[^a-z]+", " ", v.lower()).strip(): k for k, v in ISO2.items()}


def _key(value: str) -> str:
    return re.sub(r"[^a-z]+", " ", anyascii(value).lower()).strip()


def to_iso2(value: str | None) -> str | None:
    """ISO-2 code for a country name/code, or None if it can't be mapped."""
    if not value:
        return None
    raw = value.strip().rstrip(".")
    if len(raw) == 2 and raw.upper() in ISO2:
        return raw.upper()
    key = _key(raw)
    return _BY_NAME.get(key) or ALIASES.get(key)
