#!/usr/bin/env bash
# Deploy EntityIQ to Cloud Run with Cloud SQL Postgres (ticket 0054, ADR-0005).
#
# Private, scale-to-zero demo: one Cloud Run service (UI + API), no Celery
# worker (the pipeline runs inline), no Memorystore (in-memory sessions,
# max 1 instance). Safe to re-run: every step checks before creating.
#
# Usage:
#   PROJECT_ID=entityiq-demo BILLING_ACCOUNT=XXXXXX-XXXXXX-XXXXXX \
#     ./scripts/deploy-cloud-run.sh [all|infra|build|migrate|seed|service]
#
# Full walkthrough and teardown: docs/runbooks/deploy-cloud-run.md
set -euo pipefail

: "${PROJECT_ID:?set PROJECT_ID}"
REGION="${REGION:-us-central1}"
SERVICE="${SERVICE:-entityiq}"
SQL_INSTANCE="${SQL_INSTANCE:-entityiq-pg}"
SQL_TIER="${SQL_TIER:-db-f1-micro}"
DB_NAME="${DB_NAME:-entityiq}"
DB_USER="${DB_USER:-entityiq}"
AR_REPO="${AR_REPO:-entityiq}"
RUN_SA_NAME="${RUN_SA_NAME:-entityiq-run}"
STEP="${1:-all}"

RUN_SA="$RUN_SA_NAME@$PROJECT_ID.iam.gserviceaccount.com"
IMAGE_BASE="$REGION-docker.pkg.dev/$PROJECT_ID/$AR_REPO/app"
SQL_CONN="$PROJECT_ID:$REGION:$SQL_INSTANCE"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TAG="$(git -C "$ROOT" rev-parse --short HEAD)$(git -C "$ROOT" diff --quiet HEAD -- || echo -dirty)"
IMAGE="$IMAGE_BASE:$TAG"

gc() { gcloud --project "$PROJECT_ID" "$@"; }
log() { printf '\n==> %s\n' "$*"; }

# Env shared by the service and the jobs. The pipeline runs inline, so stage
# and run budgets must stay inside the service's request timeout (900 s).
COMMON_ENV="CELERY_TASK_ALWAYS_EAGER=true"
COMMON_ENV+=",ENTITYIQ_STAGE_TIMEOUT_SECONDS=60,ENTITYIQ_RUN_TIMEOUT_SECONDS=600"
# Demo instance: screen against the fictional demo list only (fixed snapshot).
COMMON_ENV+=",ENTITYIQ_SCREENING_REQUIRED_SOURCES=demo_watchlist"
COMMON_ENV+=",ENTITYIQ_SCREENING_MAX_LIST_AGE_DAYS=36500"
SECRETS="DATABASE_URL=entityiq-database-url:latest"
SECRETS+=",ENTITYIQ_SCREENING_MASTER_KEY=entityiq-screening-master-key:latest"

secret_exists() { gc secrets describe "$1" >/dev/null 2>&1; }

infra() {
  log "Project $PROJECT_ID"
  if ! gcloud projects describe "$PROJECT_ID" >/dev/null 2>&1; then
    gcloud projects create "$PROJECT_ID" --name="EntityIQ demo"
  fi
  if [ "$(gcloud billing projects describe "$PROJECT_ID" --format='value(billingEnabled)')" != "True" ]; then
    : "${BILLING_ACCOUNT:?set BILLING_ACCOUNT to link billing}"
    gcloud billing projects link "$PROJECT_ID" --billing-account="$BILLING_ACCOUNT"
  fi

  log "APIs"
  gc services enable run.googleapis.com sqladmin.googleapis.com \
    artifactregistry.googleapis.com cloudbuild.googleapis.com \
    secretmanager.googleapis.com

  log "Artifact Registry repo $AR_REPO"
  gc artifacts repositories describe "$AR_REPO" --location "$REGION" >/dev/null 2>&1 \
    || gc artifacts repositories create "$AR_REPO" --location "$REGION" \
         --repository-format docker --description "EntityIQ images"

  log "Cloud SQL $SQL_INSTANCE ($SQL_TIER, Postgres 16)"
  if ! gc sql instances describe "$SQL_INSTANCE" >/dev/null 2>&1; then
    gc sql instances create "$SQL_INSTANCE" --database-version POSTGRES_16 \
      --edition ENTERPRISE --tier "$SQL_TIER" --region "$REGION" \
      --storage-type HDD --storage-size 10 --storage-auto-increase
  fi
  gc sql databases describe "$DB_NAME" --instance "$SQL_INSTANCE" >/dev/null 2>&1 \
    || gc sql databases create "$DB_NAME" --instance "$SQL_INSTANCE"

  # The DB password only ever lives in the DATABASE_URL secret. Hex, so it
  # needs no URL- or ini-escaping. Created once; re-runs leave it alone.
  if ! secret_exists entityiq-database-url; then
    local pw
    pw="$(openssl rand -hex 24)"
    gc sql users create "$DB_USER" --instance "$SQL_INSTANCE" --password "$pw" 2>/dev/null \
      || gc sql users set-password "$DB_USER" --instance "$SQL_INSTANCE" --password "$pw"
    printf 'postgresql+psycopg://%s:%s@/%s?host=/cloudsql/%s' \
      "$DB_USER" "$pw" "$DB_NAME" "$SQL_CONN" \
      | gc secrets create entityiq-database-url --data-file=- --replication-policy automatic
  fi
  # Losing this key makes all screening subject PII unreadable (ADR-0004), so
  # it is created exactly once and never regenerated by this script.
  if ! secret_exists entityiq-screening-master-key; then
    openssl rand -base64 32 | tr -d '\n' \
      | gc secrets create entityiq-screening-master-key --data-file=- --replication-policy automatic
  fi

  log "Runtime service account $RUN_SA"
  gc iam service-accounts describe "$RUN_SA" >/dev/null 2>&1 \
    || gc iam service-accounts create "$RUN_SA_NAME" --display-name "EntityIQ Cloud Run"
  gc projects add-iam-policy-binding "$PROJECT_ID" --member "serviceAccount:$RUN_SA" \
    --role roles/cloudsql.client --condition None >/dev/null
  for s in entityiq-database-url entityiq-screening-master-key; do
    gc secrets add-iam-policy-binding "$s" --member "serviceAccount:$RUN_SA" \
      --role roles/secretmanager.secretAccessor >/dev/null
  done
}

build() {
  log "Build $IMAGE (Cloud Build)"
  (cd "$ROOT" && gc builds submit --region "$REGION" --tag "$IMAGE" .)
}

deploy_job() {  # name, command (sh -c), extra env
  local name="$1" cmd="$2" env="${3:-}"
  gc run jobs deploy "$name" --region "$REGION" --image "$IMAGE" \
    --service-account "$RUN_SA" --set-cloudsql-instances "$SQL_CONN" \
    --set-env-vars "$COMMON_ENV${env:+,$env}" --set-secrets "$SECRETS" \
    --command sh --args=-c,"$cmd" --max-retries 0 --task-timeout 900
  gc run jobs execute "$name" --region "$REGION" --wait
}

migrate() {
  log "Migrate (Cloud Run Job)"
  deploy_job entityiq-migrate "alembic upgrade head"
}

seed() {
  # Demo accounts share a public password: only for this private instance.
  log "Seed demo data (Cloud Run Job, ENTITYIQ_ALLOW_DEMO_SEED=1)"
  deploy_job entityiq-seed \
    "python -m app.seed && python -m app.demo_data && python -m app.screening.demo_data" \
    "ENTITYIQ_ALLOW_DEMO_SEED=1"
}

service() {
  log "Service $SERVICE (private, scale to zero, one instance)"
  # max-instances=1: sessions are in memory (no Redis), so a second instance
  # would not know about the first one's sign-ins.
  gc run deploy "$SERVICE" --region "$REGION" --image "$IMAGE" \
    --service-account "$RUN_SA" --add-cloudsql-instances "$SQL_CONN" \
    --set-env-vars "$COMMON_ENV" --set-secrets "$SECRETS" \
    --no-allow-unauthenticated --min-instances 0 --max-instances 1 \
    --timeout 900 --memory 1Gi --cpu 1
  log "Open it with: gcloud run services proxy $SERVICE --project $PROJECT_ID --region $REGION --port 8080"
}

case "$STEP" in
  all) infra; build; migrate; seed; service ;;
  infra) infra ;;
  build) build ;;
  migrate) migrate ;;
  seed) seed ;;
  service) service ;;
  *) echo "unknown step: $STEP" >&2; exit 2 ;;
esac
